version: "3"
services:
    database-dev:
        build: .
        image: mountainsnow/nginx-php7-mongodb-basic:0.0.3
        container_name: database-dev
        ports:
            - "80:80"
            - "27017:27017"
        volumes:
            - /Users/mountain/Sites/database-dev/web:/var/www/public
            - /Users/mountain/Sites/database-dev/database/mongodb:/data/db
