version: "3"
services:
    mongodb-dev:
        build: .
        image: mountainsnow/nginx-php7-mongodb-basic:0.0.3
        container_name: mongodb-dev
        ports:
            - "80:80"
            - "27017:27017"
        volumes:
            - /Users/mountain/Sites/mongodb-dev/web:/var/www/public
            - /Users/mountain/Sites/mongodb-dev/database:/data/db
