version: "3"
services:
    database-dev:
        image: mountainsnow/nginx-php7-mongodb-basic:latest
        container_name: database-dev
        ports:
            - "80:80"
            - "27017:27017"
        volumes:
            - /Users/mountain/Sites/database-dev/web:/var/www/public
            - /Users/mountain/Sites/database-dev/database/mongodb:/data/db
        links:
            - mysql
    mysql:
        restart: always
        image: cytopia/mysql-5.7:latest
        container_name: mysql5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root-pw
        volumes:
            - /Users/mountain/Sites/database-dev/database/mysql:/var/lib/mysql
